version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dependabot
      - pip

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dependabot
      - github-actions

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
