---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: instance

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
